### ISSUE TITLE
Add user app and lib path to environment

### ISSUE THREAD

**Issue by cnsidero** [sayerhs/cpl#19]
No support to use applications or libraries that exist in CAELUS_USER_APPBIN and CAELUS_USER_LIBBIN, respectively.

Additionally, `caelus env` does not add the aforementioned environment variables the output file.

**Comment by cnsidero** [comment]
This requires adding CAELUS_USER_APPBIN to the system PATH and CAELUS_USER_LIBBIN to the system LD_LIBRARY_PATH

**Comment by sayerhs** [comment]
Implemented in 2a26941202e0
